### ISSUE TITLE
Hello , do you remember me?

### ISSUE THREAD

**Issue by Porama6400** [DaFudgeWizzad/Ogar-Plus#1]
in the issue at https://github.com/OgarProject/Ogar/issues/175 you said you modify index.js but i think it's look same to the ogar index.js

QUESTION :

why it's look same?

i successful create shooting gamemode that you can shoot virus few month ago
do you still need help?

do you still need help?

do you remember me?

can i have your email please?

can i help your project?

**Comment by DaFudgeWizzad** [comment]
I remember, If you could help with that gamemode, I would LOVE you. XD no homo tho.

**Comment by Porama6400** [comment]
yes , i have skype
ID : opal2544

**Comment by Porama6400** [comment]
You need to create new Mode file , i will explain when we can chat

and add me please (Skype)

**Comment by DaFudgeWizzad** [comment]
I created a mode file, I just need to know what to do..

**Comment by Porama6400** [comment]
i use this code for W and it's work :

        Mode.prototype.pressW = function(gameServer,player) {

   	var client = player;
        for (var i = 0; i < client.cells.length; i++) {
        var cell = client.cells[i];

        if (!cell) {
            continue;
        }

        if (cell.mass < 32) {
            continue;
        }

        var deltaY = client.mouse.y - cell.position.y;
        var deltaX = client.mouse.x - cell.position.x;
        var angle = Math.atan2(deltaX,deltaY);

        // Get starting position
        var size = cell.getSize() + 5;
        var startPos = {
            x: cell.position.x + ( (size + 15) * Math.sin(angle) ),
            y: cell.position.y + ( (size + 15) * Math.cos(angle) )
        };

        // Remove mass from parent cell
        cell.mass -= 30
        // Randomize angle
        angle += (Math.random() * .4) - .2;

        // Create cell
        var ejected = new Entity.Virus(gameServer.getNextNodeId(), null, startPos, 15);
        ejected.setAngle(angle);
        ejected.setMoveEngineData(160, 20);

        gameServer.addNode(ejected);
        gameServer.setAsMovingNode(ejected);
        };

        };

**Comment by DaFudgeWizzad** [comment]
I get this error:

[Ogar-Plus] Set mass of  to 40
ReferenceError: Entity is not defined
    at Mode.VO.pressW (C:\Users\DaFudgeWizzad\Desktop\Ogar-Plus\src\gamemodes\VO.js:108:23)
    at PlayerTracker.update (C:\Users\DaFudgeWizzad\Desktop\Ogar-Plus\src\PlayerTracker.js:87:34)
    at GameServer.updateClients (C:\Users\DaFudgeWizzad\Desktop\Ogar-Plus\src\GameServer.js:419:39)
    at GameServer.mainLoop (C:\Users\DaFudgeWizzad\Desktop\Ogar-Plus\src\GameServer.js:389:14)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by Porama6400** [comment]
do you require it?

**Comment by DaFudgeWizzad** [comment]
This is the file:

var FFA = require('./FFA'); // Base gamemode

function VO() {
    FFA.apply(this, Array.prototype.slice.call(arguments));

    this.ID = 3;
    this.name = "Virus Off";
    this.specByLeaderboard = true;
}

module.exports = VO;
VO.prototype = new FFA();

// Gamemode Specific Functions

	VO.prototype.pressW = function(gameServer,player) {

var client = player;
    for (var i = 0; i < client.cells.length; i++) {
    var cell = client.cells[i];

    if (!cell) {
        continue;
    }

    if (cell.mass < 32) {
        continue;
    }

    var deltaY = client.mouse.y - cell.position.y;
    var deltaX = client.mouse.x - cell.position.x;
    var angle = Math.atan2(deltaX,deltaY);

    // Get starting position
    var size = cell.getSize() + 5;
    var startPos = {
        x: cell.position.x + ( (size + 15) * Math.sin(angle) ),
        y: cell.position.y + ( (size + 15) * Math.cos(angle) )
    };

    // Remove mass from parent cell
    cell.mass -= 30
    // Randomize angle
    angle += (Math.random() * .4) - .2;

    // Create cell
    var ejected = new Entity.Virus(gameServer.getNextNodeId(), null, startPos, 15);
    ejected.setAngle(angle);
    ejected.setMoveEngineData(160, 20);

    gameServer.addNode(ejected);
    gameServer.setAsMovingNode(ejected);
    };

    };
}

**Comment by DaFudgeWizzad** [comment]
You should accept me on skype

**Comment by Porama6400** [comment]
i see but i can't accept
now i sent request to you

**Comment by Porama6400** [comment]
please accept skype

**Comment by DaFudgeWizzad** [comment]
Didn't get it, my skype is seth5728

**Comment by DaFudgeWizzad** [comment]
No? I've tried many files. May you share which one you required?

**Comment by Porama6400** [comment]
This is my code

	var Entity = require('../entity');

	function Mode() {
		this.ID = -1;
		this.name = "Blank";
		this.decayMod = 1.0; // Modifier for decay rate (Multiplier)
		this.packetLB = 49; // Packet id for leaderboard packet (48 = Text List, 49 = List, 50 = Pie chart)
		this.haveTeams = false; // True = gamemode uses teams, false = gamemode doesnt use teams

		this.specByLeaderboard = false; // false = spectate from player list instead of leaderboard
	}

	module.exports = Mode;

	// Override these

	Mode.prototype.onServerInit = function(gameServer) {
		// Called when the server starts
		gameServer.run = true;
	};

	Mode.prototype.onTick = function(gameServer) {
		// Called on every game tick 
	};

	Mode.prototype.onChange = function(gameServer) {
		// Called when someone changes the gamemode via console commands
	};

	Mode.prototype.onPlayerInit = function(player) {
		// Called after a player object is constructed
	};

	Mode.prototype.onPlayerSpawn = function(gameServer,player) {
		// Called when a player is spawned
		player.color = gameServer.getRandomColor(); // Random color
		gameServer.spawnPlayer(player);
	};

	Mode.prototype.pressQ = function(gameServer,player) {
		// Called when the Q key is pressed
		if (player.spectate) {
			gameServer.switchSpectator(player);
		}
	};

	Mode.prototype.pressW = function(gameServer,player) {
		// Called when the W key is pressed
		//var newVirus = new Entity.Virus(this.getNextNodeId(), null, player.position(), 30);
		//newVirus.setAngle(player.getAngle());
		//newVirus.setMoveEngineData(200, 20);
		//this.addNode(newVirus);
		//this.setAsMovingNode(newVirus);
		//gameServer.ejectMass(player);
		var client = player;
	for (var i = 0; i < client.cells.length; i++) {
			var cell = client.cells[i];

			if (!cell) {
				continue;
			}

			if (cell.mass < 32) {
				continue;
			}

			var deltaY = client.mouse.y - cell.position.y;
			var deltaX = client.mouse.x - cell.position.x;
			var angle = Math.atan2(deltaX,deltaY);

			// Get starting position
			var size = cell.getSize() + 5;
			var startPos = {
				x: cell.position.x + ( (size + 15) * Math.sin(angle) ),
				y: cell.position.y + ( (size + 15) * Math.cos(angle) )
			};

			// Remove mass from parent cell
			cell.mass -= 30
			// Randomize angle
			angle += (Math.random() * .4) - .2;

			// Create cell
			var ejected = new Entity.Virus(gameServer.getNextNodeId(), null, startPos, 15);
			ejected.setAngle(angle);
			ejected.setMoveEngineData(160, 20);

			gameServer.addNode(ejected);
			gameServer.setAsMovingNode(ejected);
	};
	};

	Mode.prototype.pressSpace = function(gameServer,player) {
		// Called when the Space bar is pressed
		gameServer.splitCells(player);
	};

	Mode.prototype.onCellAdd = function(cell) {
		// Called when a player cell is added
	};

	Mode.prototype.onCellRemove = function(cell) {
		// Called when a player cell is removed
	};

	Mode.prototype.onCellMove = function(x1,y1,cell) {
		// Called when a player cell is moved
	};

	Mode.prototype.updateLB = function(gameServer) {
		// Called when the leaderboard update function is called
	};

**Comment by Porama6400** [comment]
Oh , finally i can see your skype

**Comment by DaFudgeWizzad** [comment]
Thanks, you get full credit for the VO gamemode.
